SELECT 
GFILIAL.NOME AS EMITENTE,
GFILIAL.CGC AS CNPJ,
GFILIAL.RUA AS RUA,
GFILIAL.NUMERO
FROM U_CFL8U4_RM.FLAN
LEFT JOIN U_CFL8U4_RM.GFILIAL
ON FLAN.CODFILIAL = GFILIAL.CODFILIAL
WHERE
FLAN.IDLAN = 507685

