-- CABEÇALHO 
'PERÍODO: XX/XX/XXXX Á XX/XX/XXXX (UTILIZAR FUNÇÃO PARA TRAZER ESSES DADOS DOS FILTROS)'


-- CORPO 
'DATA:' TMOV.DATASAIDA 'DATA DA SAÍDA'
'TRIBUTO:' TTRBMOV.CODTRB 'CÓDIGO DO TRIBUTO'
'BASE DE CÁLCULO:' TTRBMOV.BASEDECALCULO 'BASE DE CÁLCULO'
'ALÍQUOTA' TTRBMOV.ALIQUOTA 'ALÍQUOTA'
'VALOR' TTRBMO.VALOR 'VALOR'
'FILIAL' TMOV.CODFILIAL 'CÓDIGO DA FILIAL'
'Nº DO MOVIMEMNTO' TMOV.NUMEROMOV 'NÚMERO DO MOVIMENTO'
'FORNECEDOR' FCFO.NOME 'NOME'
'CNPJ' FCFCO.CGCCFO 'CNPJ'
'CENTRO DE CUSTO' TITMMOV.CODCUSTO 'CENTRO DE CUSTO'

-- CAMPOS CHAVE
TMOV.CODTMV - 'CÓDIGO DO TIPO DE MOVIMENTO'
TMOV.TIPO - 'TIPO'
TMOV.DATAEMISSAO -' DATA DA EMISSÃO'
GFILIAL.NOME - 'NOME DA FILIAL'

--FILTROS
'TRIBUTO:' TTRBMOV.CODTRB 'CÓDIGO DO TRIBUTO' LIKE 
'FILIAL' TMOV.CODFILIAL 'CÓDIGO DA FILIAL' >= E <=
'DATA:' TMOV.DATASAIDA 'DATA DA SAÍDA' >= E <=











