SELECT EMPREGADOR.EMITENTE                    EMITENTE_1,
       EMPREGADOR.TIPOCAT                     TIPOCAT_2,
       EMPREGADOR.NOME                        RAZSOCIALNOME_3,
       EMPREGADOR.CGC                         TIPO_4,
       EMPREGADOR.ATIVECONOMICA               CNAE_5,
       EMPREGADOR.ENDERECO                    ENDRAVNCOMP_6,
       EMPREGADOR.BAIRRO                      BAIRRO_6,
       EMPREGADOR.CEP                         CEP_6,
       EMPREGADOR.CIDADE                      MUNICIPIO_7,
       EMPREGADOR.ESTADO                      UF_8,
       EMPREGADOR.TELEFONE                    TELEFONE_9,
       ACIDENTADO.NOMEFUNC                    NOME_10,
       ACIDENTADO.NOMEDEPEND                  NOMEDAMAE_11,
       ACIDENTADO.DTNASCIMENTO                DATANASC_12,
       ACIDENTADO.SEXO                        SEXO_13,
       ACIDENTADO.ESTADOCIVIL                 ESTADOCIVIL_14,
       ACIDENTADO.CARTEIRATRAB                CARTEIRATRAB_15,
       ACIDENTADO.SERIECARTTRAB               SERIECARTTRAB_15,
       ACIDENTADO.DTCARTTRAB                  DTCARTTRAB_15,
       ACIDENTADO.UFCARTTRAB                  UFCARTTRAB_16,
       ACIDENTADO.SALARIO                     SALARIO_17,
       ACIDENTADO.CARTIDENTIDADE              CARTIDENTIDADE_18,
       ACIDENTADO.DTEMISSAOIDENT              DTEMISSAOIDENT_18,
       ACIDENTADO.ORGEMISSORIDENT             ORGEMISSORIDENT_18,
       ACIDENTADO.UFCARTIDENT                 UFCARTIDENT_19,
       ACIDENTADO.PISPASEPNIT                 PISPASEPNIT_20,
       ACIDENTADO.ENDERECO                    ENDRAVNCOMP_21,
       ACIDENTADO.BAIRRO                      BAIRRO_21,
       ACIDENTADO.CEP                         CEP_21,
       ACIDENTADO.CIDADE                      MUNICIPIO_22,
       ACIDENTADO.ESTADO                      UF_23,
       ACIDENTADO.TELEFONE1                   TELEFONE_24,
       ACIDENTADO.NOMEFUNCAO                  NOMEOCUPACAO_25,
       ACIDENTADO.CBO2002                     CBO_26,
       ACIDENTADO.FILIACAOPREVIDENCIA         FILIACAOPREVIDSOCIAL_27,
       ACIDENTADO.APOSENTADO                  APOSENTADO_28,
       ACIDENTADO.AREA                        AREA_29,
       ACIDENTEDOENCA.DATAHORA                DATA_30HORA_31_ACIDENTE,
       ACIDENTEDOENCA.HORASTRAB               APOSQTSHRSDETRABALHO_32,
       ACIDENTEDOENCA.TIPO                    TIPO_33,
       ACIDENTEDOENCA.HOUVEAFASTAMENTO        HOUVEAFASTAMENTO_34,
       ACIDENTEDOENCA.DIASANTECEDACIDENTE     ULTIMODIATRABALHADO_35,
       ACIDENTEDOENCA.NOMELOCALTRAB           NOMELOCALTRAB_36,
       ACIDENTEDOENCA.LOCALACIDENTE           LOCALACIDENTE_37,
       ACIDENTEDOENCA.CGC                     CGC_38,
       ACIDENTEDOENCA.UFLOCALACIDENTE         UFLOCALACIDENTE_39,
       ACIDENTEDOENCA.MUNLOCALACIDENTE        MUNLOCALACIDENTE_40,
       ACIDENTEDOENCA.NATUREZA                NATUREZA_41,
       ACIDENTEDOENCA.AGENTECAUSADOR          AGENTECAUSADOR_42,
       ACIDENTEDOENCA.DESCSITUACAO            DESCSITUACAO_43,
       ACIDENTEDOENCA.HOUVEREGISPOLICIAL      HOUVEREGISPOLICIAL_44,
       ACIDENTEDOENCA.HOUVEMORTE              HOUVEMORTE_45,
       TESTEMUNHA1.NOME                       NOMETEST1_46,
       TESTEMUNHA1.ENDERECO                   ENDTEST1_47,
       TESTEMUNHA1.BAIRRO                     BAIRROTEST1_47,
       TESTEMUNHA1.CEP                        CEPTEST1_47,
       TESTEMUNHA1.CIDADE                     MUNICIPIOTEST1_48,
       TESTEMUNHA1.ESTADO                     ESTADOTEST1_49,
       TESTEMUNHA1.TELEFONE1                  TELEFONE1TEST1_49,
       TESTEMUNHA2.NOME                       NOMETEST2_50,
       TESTEMUNHA2.ENDERECO                   ENDERECOTEST2,
       TESTEMUNHA2.BAIRRO                     BAIRROTEST2_51,
       TESTEMUNHA2.CEP                        CEPTEST2_51,
       TESTEMUNHA2.CIDADE                     CIDADETEST2_52,
       TESTEMUNHA2.ESTADO                     ESTADOTEST2_53,
       TESTEMUNHA2.TELEFONE1                  TELEFONE1TEST2_53,
       ATESTADOMEDICO.UNIDATENDIMENTO         UNIDATENDIMENTO_54,
       ATESTADOMEDICO.DATAMEDICA              DATAMED_55_HORA_56,
       ATESTADOMEDICO.HOUVEINTERNACAO         HOUVEINTERNACAO_57,
       ATESTADOMEDICO.DURACAOTRATAMENTO       DURACAOTRATAMENTO_58,
       ATESTADOMEDICO.AFASTADURANTETRATAMENTO AFASTADURANTETRATAMENTO_59,
       ATESTADOMEDICO.NATUREZA                NATUREZA_60,
       ATESTADOMEDICO.DIAGNOSTICO             DIAGNOSTICO_61,
       ATESTADOMEDICO.CID                     CID10_62,
       ATESTADOMEDICO.VALMEMO                 OBSERVACOES_63
FROM   (SELECT VOCORRENCIA.CODCOLIGADA,
               VOCORRENCIA.CODOCORRENCIA,
               VOCORRENCIA.EMITENTE,
               VOCORRENCIA.TIPOCAT,
               GCOLIGADA.NOME,
               PSECAO.CGC,
               PSECAO.ATIVECONOMICA,
               PSECAO.RUA
               || ', '
               || PSECAO.NUMERO
               || ' '
               || PSECAO.COMPLEMENTO ENDERECO,
               PSECAO.BAIRRO,
               PSECAO.CEP,
               PSECAO.CIDADE,
               PSECAO.ESTADO,
               PSECAO.TELEFONE
        FROM   PFUNC
               INNER JOIN VOCORRENCIA
                 ON PFUNC.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA
                    AND PFUNC.CHAPA = VOCORRENCIA.CHAPA
               INNER JOIN PSECAO
                 ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
                    AND PSECAO.CODIGO = PFUNC.CODSECAO
               INNER JOIN GCOLIGADA
                 ON GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA
        WHERE  GCOLIGADA.CODCOLIGADA = :CODCOLIGADA
               AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR2(10))) EMPREGADOR
       JOIN (SELECT VOCORRENCIA.CODCOLIGADA,
                    VOCORRENCIA.CODOCORRENCIA,
                    PFUNC.NOME             NOMEFUNC,
                    PFDEPEND.NOME          NOMEDEPEND,
                    PPESSOA.DTNASCIMENTO,
                    CASE
                      WHEN PPESSOA.SEXO = 'M' THEN 1
                      ELSE 3
                    END                    SEXO,
                    CASE
                      WHEN PPESSOA.ESTADOCIVIL = 'S' THEN 1
                      WHEN PPESSOA.ESTADOCIVIL IN ('C','E') THEN 2
                      WHEN PPESSOA.ESTADOCIVIL = 'V' THEN 3
                      WHEN PPESSOA.ESTADOCIVIL = 'D'  THEN 4
                      WHEN PPESSOA.ESTADOCIVIL = 'O' THEN 5 
                    END                    ESTADOCIVIL,
                    PPESSOA.CARTEIRATRAB,
                    PPESSOA.SERIECARTTRAB,
                    PPESSOA.DTCARTTRAB,
                    PPESSOA.UFCARTTRAB,
                    PFUNC.SALARIO,
                    PPESSOA.CARTIDENTIDADE,
                    PPESSOA.DTEMISSAOIDENT,
                    PPESSOA.ORGEMISSORIDENT,
                    PPESSOA.UFCARTIDENT,
                    CASE
                      WHEN PFUNC.CI IS NULL THEN PFUNC.PISPASEP
                      ELSE PFUNC.CI
                    END                    PISPASEPNIT,
                    PPESSOA.RUA
                    || ', '
                    || PPESSOA.NUMERO
                    || ' '
                    || PPESSOA.COMPLEMENTO ENDERECO,
                    PPESSOA.BAIRRO,
                    PPESSOA.CEP,
                    PPESSOA.CIDADE,
                    PPESSOA.ESTADO,
                    PPESSOA.TELEFONE1,
                    PFUNCAO.NOME           NOMEFUNCAO,
                    PFUNCAO.CBO2002,
                    VOCORRENCIA.FILIACAOPREVIDENCIA,
                    CASE
                      WHEN PFUNC.APOSENTADO = 1 THEN PFUNC.APOSENTADO
                      ELSE 2
                    END                    APOSENTADO,
                    CASE
                      WHEN PFUNC.CODTIPO <> 'R' THEN 1
                      ELSE 2
                    END                    AREA
             FROM   VOCORRENCIA
                    JOIN PFUNC
                      ON PFUNC.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA
                         AND PFUNC.CHAPA = VOCORRENCIA.CHAPA
                    JOIN PPESSOA
                      ON PPESSOA.CODIGO = PFUNC.CODPESSOA
                    JOIN PFUNCAO
                      ON PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA
                         AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO
                    LEFT JOIN PFDEPEND
                      ON PFDEPEND.CODCOLIGADA = PFUNC.CODCOLIGADA
                         AND PFDEPEND.CHAPA = PFUNC.CHAPA
                         AND PFDEPEND.GRAUPARENTESCO = '7'
             WHERE  VOCORRENCIA.CODCOLIGADA = :CODCOLIGADA
                    AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR2(10))) ACIDENTADO
         ON EMPREGADOR.CODCOLIGADA = ACIDENTADO.CODCOLIGADA
            AND EMPREGADOR.CODOCORRENCIA = ACIDENTADO.CODOCORRENCIA
       JOIN (SELECT VOCORRENCIA.CODCOLIGADA,
                    VOCORRENCIA.CODOCORRENCIA,
                    VOCORRENCIA.DATAHORA,
                    VOCORRENCIA.HORASTRAB,
                    SUBSTR(VOCORRENCIA.CODTIPOOCORRENCIA, -1, 1) TIPO,
                    CASE
                      WHEN VOCORRENCIA.HOUVEAFASTAMENTO = '0' THEN 1
                      ELSE 2
                    END                                          HOUVEAFASTAMENTO,
                    VOCORRENCIA.DIASANTECEDACIDENTE,
                    (SELECT DESCRICAO 
                     FROM GCONSIST 
                     WHERE CODTABELA = 'CATTIPOLOC' 
                     AND APLICACAO = 'V' 
                     AND CODCLIENTE = VOCORRENCIA.LOCALACIDENTEINSS) NOMELOCALTRAB,
                    VOCORRENCIA.LOCALACIDENTE,
                    CASE WHEN VOCORRENCIA.LOCALACIDENTEINSS = '2'
					     THEN CASE WHEN VOCORRENCIA.NROINSCRICAO IS NOT NULL THEN VOCORRENCIA.NROINSCRICAO
					        	   WHEN VOCORRENCIA.CGCLOCALACIDENTE IS NOT NULL THEN VOCORRENCIA.CGCLOCALACIDENTE
					  			   ELSE PSECAO.CGC
					  	       END
					  	 ELSE ''
					 END CGC,
                    VOCORRENCIA.UFLOCALACIDENTE,
                    VOCORRENCIA.MUNLOCALACIDENTE,
                    (SELECT lISTAGG(VNATUREZA.NATUREZA, ', ') WITHIN GROUP (ORDER BY VNATUREZA.NATUREZA)
                      FROM VOCORRENCIA  LEFT JOIN
                      		  VOCORRENCIAPARTEATINGIDA  ON VOCORRENCIAPARTEATINGIDA.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA 
                      		   AND VOCORRENCIAPARTEATINGIDA.CODOCORRENCIA = VOCORRENCIA.CODOCORRENCIA JOIN  
                      		  VNATUREZA  ON VNATUREZA.CODNATUREZA = VOCORRENCIAPARTEATINGIDA.CODNATUREZA
                    		 WHERE VOCORRENCIA.CODCOLIGADA = :CODCOLIGADA 
                    		 AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR(10))) NATUREZA,
                    (SELECT lISTAGG(VPPRAFONTEGERA.NOME, ', ') WITHIN GROUP (ORDER BY VPPRAFONTEGERA.NOME)
                    		 FROM VOCORRENCIA  LEFT JOIN
                      		  VOCORRENCIAAGENTECAUSADOR  ON VOCORRENCIAAGENTECAUSADOR.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA 
                      		   AND VOCORRENCIAAGENTECAUSADOR.CODOCORRENCIA = VOCORRENCIA.CODOCORRENCIA JOIN  
                      		  VPPRAFONTEGERA  ON VPPRAFONTEGERA.CODFONTEGERA = VOCORRENCIAAGENTECAUSADOR.CODFONTEGERA
                    		 WHERE VOCORRENCIA.CODCOLIGADA = :CODCOLIGADA 
                    		 AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR(10))) AGENTECAUSADOR,
                    VOCORRENCIA.DESCRICAO                        DESCSITUACAO,
                    CASE
                      WHEN VOCORRENCIA.REGPOLICIAL = 0 THEN 2
                      ELSE 1
                    END                                          HOUVEREGISPOLICIAL,
                    CASE
                      WHEN VOCORRENCIA.MORTE = 0 THEN 2
                      ELSE 1
                    END                                          HOUVEMORTE
             FROM   VOCORRENCIA
                    LEFT JOIN VLOCALTRABALHO
                      ON VOCORRENCIA.CODLOCALTRABALHO = VLOCALTRABALHO.CODLOCALTRABALHO
                         AND VOCORRENCIA.CODCOLIGADA = VLOCALTRABALHO.CODCOLIGADA
                    LEFT JOIN PSECAO
                      ON PSECAO.CODIGO = VLOCALTRABALHO.CODSECAO
                         AND PSECAO.CODCOLIGADA = VLOCALTRABALHO.CODCOLIGADA
             WHERE  VOCORRENCIA.CODCOLIGADA = :CODCOLIGADA
                    AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR2(10))) ACIDENTEDOENCA
         ON ACIDENTEDOENCA.CODCOLIGADA = ACIDENTADO.CODCOLIGADA
            AND ACIDENTEDOENCA.CODOCORRENCIA = ACIDENTADO.CODOCORRENCIA
       LEFT JOIN (SELECT VTESTEMUNHACAT.CODCOLIGADA,
                    VTESTEMUNHACAT.CODOCORRENCIA,
                    PPESSOA.NOME,
                    PPESSOA.RUA
                    || ', '
                    || PPESSOA.NUMERO
                    || ' '
                    || PPESSOA.COMPLEMENTO ENDERECO,
                    PPESSOA.BAIRRO,
                    PPESSOA.CEP,
                    PPESSOA.CIDADE,
                    PPESSOA.ESTADO,
                    PPESSOA.TELEFONE1
             FROM   VTESTEMUNHACAT
                    JOIN PPESSOA
                      ON VTESTEMUNHACAT.CODPESSOA = PPESSOA.CODIGO
                         AND VTESTEMUNHACAT.CODTESTEMUNHA = 1
             WHERE  VTESTEMUNHACAT.CODCOLIGADA = :CODCOLIGADA
                    AND VTESTEMUNHACAT.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR2(10))) TESTEMUNHA1
         ON ACIDENTADO.CODCOLIGADA = TESTEMUNHA1.CODCOLIGADA
            AND ACIDENTADO.CODOCORRENCIA = TESTEMUNHA1.CODOCORRENCIA
       LEFT JOIN (SELECT VTESTEMUNHACAT.CODCOLIGADA,
                    VTESTEMUNHACAT.CODOCORRENCIA,
                    PPESSOA.NOME,
                    PPESSOA.RUA
                    || ', '
                    || PPESSOA.NUMERO
                    || ' '
                    || PPESSOA.COMPLEMENTO ENDERECO,
                    PPESSOA.BAIRRO,
                    PPESSOA.CEP,
                    PPESSOA.CIDADE,
                    PPESSOA.ESTADO,
                    PPESSOA.TELEFONE1
             FROM   VTESTEMUNHACAT
                    JOIN PPESSOA
                      ON VTESTEMUNHACAT.CODPESSOA = PPESSOA.CODIGO
                         AND VTESTEMUNHACAT.CODTESTEMUNHA = 2
             WHERE  VTESTEMUNHACAT.CODCOLIGADA = :CODCOLIGADA
                    AND VTESTEMUNHACAT.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR2(10))) TESTEMUNHA2
         ON TESTEMUNHA2.CODCOLIGADA = ACIDENTADO.CODCOLIGADA
            AND TESTEMUNHA2.CODOCORRENCIA = ACIDENTADO.CODOCORRENCIA
       LEFT JOIN (SELECT VOCORRENCIA.CODCOLIGADA,
                    VOCORRENCIA.CODOCORRENCIA,
                    VOCORRENCIA.UNIDATENDIMENTO,
                    VOCORRENCIA.DATAMEDICA,
                    CASE
                      WHEN VOCORRENCIA.INTERNACAO = 1 THEN VOCORRENCIA.INTERNACAO
                      ELSE 2
                    END HOUVEINTERNACAO,
                    VOCORRENCIA.DURACAOTRATAMENTO,
                    CASE
                      WHEN VOCORRENCIA.HOUVEAFASTAMENTO = '0' THEN 1
                      ELSE 2
                    END AFASTADURANTETRATAMENTO,
                    (SELECT lISTAGG(VNATUREZACAT.NATUREZA, ', ') WITHIN GROUP (ORDER BY VNATUREZACAT.NATUREZA)
                    		 FROM VOCORRENCIA  LEFT JOIN
                      		  VOCORRENCIANATUREZAMEDICA  ON VOCORRENCIANATUREZAMEDICA.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA 
                      		   AND VOCORRENCIANATUREZAMEDICA.CODOCORRENCIA = VOCORRENCIA.CODOCORRENCIA JOIN  
                      		  VNATUREZACAT  ON VNATUREZACAT.CODNATUREZA = VOCORRENCIANATUREZAMEDICA.CODNATUREZA
                    		 WHERE VOCORRENCIA.CODCOLIGADA = :CODCOLIGADA 
                    		 AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR(10))) NATUREZA,
                    VOCORRENCIA.DIAGNOSTICO,
                    VOCORRENCIA.CID,
                    VMEMO.VALMEMO
             FROM   VOCORRENCIA
                    LEFT JOIN VMEMO
                      ON VMEMO.ID = VOCORRENCIA.IDMEMOMEDICO
             WHERE  VOCORRENCIA.CODCOLIGADA = :CODCOLIGADA
                    AND VOCORRENCIA.CODOCORRENCIA = CAST(:CODOCORRENCIA_S AS VARCHAR2(10))) ATESTADOMEDICO
         ON ACIDENTADO.CODCOLIGADA = ATESTADOMEDICO.CODCOLIGADA
            AND ACIDENTADO.CODOCORRENCIA = ATESTADOMEDICO.CODOCORRENCIA 